### ISSUE TITLE
דיבייט

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#1]
**דיבייט - להתווכח נכון**
הרעיון: זירה דיגיטלית מצולמת/כתובה. (כמו באטל, כמו עימות טלויזיוני) אליה נכנסים 2 מתמודדים בכל דיבייט בנושאים שונים ומוגדרים מראש, עם חוקים וזמן מוגבלים, 

אפשרויות:
 לצפות בדיבייט, 
 לשפוט את הדיבייט.
חוקים
לפני התחלת הדיבייט כל מתמודד, ייקבל הסבר/הבהרה לגבי החוקים.

ישנם שלושה סיבובים, בכל סיבוב … 

לדוג מסגרת זמנים:
סיבב ראשון - של שלוש דקות לכל מתמודד.
סבב שני - של דקה וחצי לכל מתמודד.
סבב שלישי -  של חצי דקת סיכום לכל מתמודד.
סה"כ 10 דקות עימות. במהלכן המתמודד שאינו מדבר מושתק, ויכול לבחור בתורו, האם להגיב, או להתעלם.

צריך לראות אם אפשר טכנולוגית לאכוף מיידית נגד אלימות מילולית, שיימינג, או כל פוגענות.

אפשרות לדיבייט כתוב, דיבייט קולי (אודיו), דיבייט מצולם
בהמשך  תהיה אפשרות לשיתוף הסיבוב/הדיבייט. 
הקלטה, לשלוח לייב לרשתות (פייסבוק,אינסטגרם,טיקטוק,טוויטר)
אפשר להזמין צופים לראות דיבייטים.

אפיון אתר/אפליקציה

המטרה: זירת וויכוחים עם סבבי זמן מוגדרים, וכללי התנהגות, שייתנו כלים לאנשים להתווכח חכם יותר ונכון יותר.

איך זה יעבוד?

בחירת נושא מרשימת נושאים אפשריים.
בחירת עמדה - בעד/נגד.
מציאת התאמה נגדית מהמאגר - הדאטה 
כניסה לזירה.
הזירה בעצם תהיה כמו 2 חלונות זום/לייב.
עם שעון עצר, שם הנושא. עמדה דולקת למדבר עם שעון טיימר, והשתקה אוטומתית למי שלא מדבר

דברים שעוד צריך לבחון, זה איך הצופים שותפים והאם יש להם השפעה על הניקוד,  

פיצ'רים

התחברות/הרשמה
אפשרות להתחבר/להתממשק דרך משמתמש בגוגל, פייסבוק,אינסטגרם,טיקטוק,טוויטר.
פרופיל אמיתי - מניעת אפשרות לזייף פרופיל.
(אולי בהמשך תהיה אפשרות לשדר משם בלייב את העימות ואז הלייקים והצפיות שאקבל יכולים להשפיע על הציון שלי בדיבייט צריך לבדוק האם הפיתרון קיים)

זירת משתתפים/זירת צופים
תהיה אפשרות להצטרף כצופה לדיבייטים חיים/לצפות במוקלטים/לתזמן תזכורות לעתידיים
אתה מעוניין להשתתף / לצפות בדיבייט?
רק לצפות - (בהמשך - באיזו מדינה? באיזו שפה? ישראל + עברית)
באיזה נושא תרצה לצפות? רשימה של נושאים רלוונטים: 
לדוגמה: הרפורמה המשפטית, סכרת, זיהום סביבתי, חרדים/חילונים
דת ומדינה

הרפורמה המשפטית: אתה בעד/נגד?
בעד
המערכת מחפשת לך מתנגדים……..

המערכת מצאה את אביטל מגבעתיים, היא מתנגדת לרפורמה.
האם תרצה להתווכח איתה עכשיו? (אולי אפשר לתזמן בהמשך למועד מאוחר יותר
יש התאמה

ניקוד

ניקןד - בחזון הניקוד יחולק ל-2. 
1. ע"י רוב הצופים.
2 ע"י שיפוט המערכת של בלתי מעורבים.

מה הקריטריונים לניקוד?

קללות, גידופים, אלימות מילולית,
פנייה, האשמה, השפלה, אישית, הכללה, 
וואטאבאוטאיזם,

בעיות – איך מודדים הצלחה/ניצחון איך נותנים ניקוד?
על מה יורד ניקוד (קללות, הסתה, דיבור לא על הנושא.)
על מה עולה ניקוד (טיעונים, נימוס וכבוד, ידע, אסמכתאות)
אפשרות ראשונה – קהל מצביע בכל סיום סבב. תוכל להצביע פעם אחת, רק אם צפית בסיבוב שלם.
אפשרות שניה - שופט אובייקטיבי אנושי/רובוטי
מי לדעתך צודק יותר,

בעיות נוספות:
איך אוכפים חוקים ושפה נקייה.?
איך מונעים אלימות, קללות, השפלות שיימינג?
איך אני חושף את הדיבייט שאני הולך להשתתף בו/ השתתפתי בו, לקהל רחב, ברשתות.

**Comment by eranws** [comment]
@aansbacher 
בוא נחלק לנושאים, יש כאן כל מיני שאלות ומשימות.
