### ISSUE TITLE
זמנים

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#10]
לפני התחלת הדיבייט כל מתמודד, ייקבל הסבר/הבהרה לגבי החוקים.

ישנם שלושה סיבובים, בכל סיבוב …

לדוג' מסגרת זמנים:
סיבב ראשון - של שלוש דקות לכל מתמודד.
סיבוב שני - של דקה וחצי לכל מתמודד.
סיבוב שלישי - של חצי דקת סיכום לכל מתמודד.

סה"כ 10 דקות עימות. במהלכן המתמודד שאינו מדבר מושתק, ויכול לבחור בתורו, האם להגיב, או להתעלם.

**Comment by eranws** [comment]
merge into #28
