### ISSUE TITLE
אכיפה

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#11]
עריכה:
Moderation of BAD Behavior טיפול באלימות מילולית, שיימינג, או כל פוגענות.

**Comment by eranws** [comment]
Technically possible (everything is), but sentence and sentiment analysis are hard.

For the pilot we can start with a simple Blacklist 🖤🐈‍⬛ of bad words, like the seven you cannot say on television 📺

**Comment by eranws** [comment]
How do you 'enforce' it?
- Censorship 
- Education
- Scoring
- Shaming

Sometimes 'bad words' are useful, abd maybe even necessary...

**Comment by eranws** [comment]
What is Bad? There is a spectrum between funny, sarcastic, sassy and toxic violence and hatred.

**Comment by aansbacher** [comment]
מתלבט אם הנושא שייך לחוקים או לניקוד

**Comment by eranws** [comment]
איפשהו על התפר. אפשר להגיד שהתבטאות עם ניקוד נמוך מזכה בכרטיס אדום.

**Comment by aansbacher** [comment]
נושא שחייב בירור

**Comment by eranws** [comment]
כדי שיהיה ברור לכולם, אפשר להגיד שבתור התחלה אפשר לקחת הנחות מקילות בכול התחומים:
- שופט אנושי. זה קשה לנתח טקסט ובמיוחד טקסט פוגעני יכול להיות מרומז, או תלוי הקשר.
- אפשר לחלק באופן גס לפי תגובה: רעילה, סתומה או מועילה
- ניקוד של מינוס שלוש או מספר כלשהו זה כרטיס אדום והפסד, הרחקה לצמיתות. יהיה נחמד לעשות לזה קיו איי פא%$# שי***
- פלטפורמה של התכתבות. ברור לך שההודעה שלך עוברת איזשהו סינון לפני שהיא מגיעה לצד השני חו״ח, או לציבור קו״ח.
זה די סטנדרטי בפורומים של פעם. יש תפקיד של מנהל תוכן, moderator, צנזור

**Comment by eranws** [comment]
נמזג לתוך #28
