### ISSUE TITLE
שיתוף הדיבייט.

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#13]
שיתוף הזמנה לצפייה בדיבייט/ הקלטה, לשלוח לייב לרשתות (פייסבוק,אינסטגרם,טיקטוק,טוויטר)
אפשר להזמין צופים לראות דיבייטים.

**Comment by eranws** [comment]
closing. Let's focus on critical features for the pilot.
Login/Social/sharing etc. are external to the actual experience.
