### ISSUE TITLE
תרשים זרימה

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#14]
התחברות/הרשמה
אפשרות להתחבר/להתממשק דרך משתמש בגוגל, פייסבוק,אינסטגרם,טיקטוק,טוויטר.
(אולי בהמשך תהיה אפשרות לשדר משם בלייב את העימות ואז הלייקים והצפיות שאקבל יכולים להשפיע על הציון שלי בדיבייט צריך לבדוק האם הפיתרון קיים)

זירת משתתפים/זירת צופים
תהיה אפשרות להצטרף כצופה לדיבייטים חיים/לצפות במוקלטים/לתזמן תזכורות לעתידיים
אתה מעוניין להשתתף / לצפות בדיבייט?
רק לצפות - (בהמשך - באיזו מדינה? באיזו שפה? ישראל + עברית)
באיזה נושא תרצה לצפות? רשימה של נושאים רלוונטים: 
לדוגמה: הרפורמה המשפטית, סכרת, זיהום סביבתי, חרדים/חילונים
דת ומדינה

הרפורמה המשפטית: אתה בעד/נגד?
בעד
המערכת מחפשת לך מתנגדים……..
המערכת מצאה את אביטל מגבעתיים, היא מתנגדת לרפורמה.
האם תרצה להתווכח איתה עכשיו? (אולי אפשר לתזמן בהמשך למועד מאוחר יותר
יש התאמה

**Comment by shantupai** [comment]
אפשר גם שאתה מקליט איזה כמה מילים על הדברים העיקריים שאת.ה להוטים להתווכח עליהון

**Comment by aansbacher** [comment]
אהבתי מאוד, רושם לעצמך? או רושם לכולם/ליריב?
