### ISSUE TITLE
ניקוד

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#15]
הניקוד יינתן ע"י הצופים. כל צופה שצפה בסיבוב יוכל לנקד אותו.

מה הקריטריונים לניקוד?
**ניקוד שלילי**
קללות, גידופים, אלימות מילולית,
פנייה, האשמה, השפלה, אישית, הכללה,
בין -3-1

ניקוד חיובי
על משפט?
על היגד?

בעיות – איך מודדים הצלחה/ניצחון איך נותנים ניקוד?
על מה יורד ניקוד (קללות, הסתה, דיבור לא על הנושא.)
על מה עולה ניקוד (טיעונים, נימוס וכבוד, ידע, אסמכתאות)
אפשרות ראשונה – קהל מצביע בכל סיום סבב. תוכל להצביע פעם אחת, רק אם צפית בסיבוב שלם.
אפשרות שניה - שופט אובייקטיבי אנושי/רובוטי
מי לדעתך צודק יותר,

בעיות נוספות:
איך אוכפים חוקים ושפה נקייה.?
איך מונעים אלימות, קללות, השפלות שיימינג?
איך אני חושף את הדיבייט שאני הולך להשתתף בו/ השתתפתי בו, לקהל רחב, ברשתות.

**Comment by shantupai** [comment]
אפשר שיהיו תפקידים גם לצופים, נגיד משגיח אלימות
וזו גם דרך לצבור ניקוד, אני בתור צופה מקבל נקודות בפלטפורמה ו/או זה נכנס לפרופיל שלי (היה משגיח אלימות בשלושה עימותים וקיבל ציור עובר/לא עובר מהמתמודדים

**Comment by aansbacher** [comment]
החלטנו שהשופטים כרגע הם הצופים.
אז איך אנחנו נותנים להם לנקד.
ואת מה בעצם הם מנקדים? את הסיבוב, את המשפט.
ניקוד חיובי?/שלילי

**Comment by aansbacher** [comment]
הצופים שותפים ויש להם השפעה על הניקוד,
משתתף/צופה/שופט.
רמת ההבנה שלך בנושא - מומחה, לא פראייר, באתי ללמוד.

**Comment by eranws** [comment]
טוב אני קורא ומתרגש
- גם מזה שיש פה התפתחות מעניינת
- גם מזה שזה נעים ארגונומית לכתוב את המילה ,קורא, קורא קוראקוראקורא

### התפתחות מעניינת
אני קורא את זה ברצף ותייג לעצמי בראש:

איך אוכפים חוקים ושפה נקייה.? איך מונעים אלימות, קללות, השפלות שיימינג?
  - אכיפה!

- איך אני חושף את הדיבייט שאני הולך להשתתף בו/ השתתפתי בו, לקהל רחב, ברשתות.
  - שיתוף!

ואז אחרי יומיים: אפשר שיהיו תפקידים גם לצופים, נגיד משגיח אלימות
- שיתוף אכיפה!

**Comment by eranws** [comment]
מזג ל#28
