### ISSUE TITLE
פלטפורמה של הודעות קוליות

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#16]
צ'אנקים מובנים של זמני הקלטות. 
מתמלל הקלטות. למשפטים קצרים 

ציר הזמן - עם אפשרות להגיב על משפטים,

הקלטה של דקה:
תמלול:
אני חושב משמע אני קיים-
וש.......-
וש.......-
נגמר הזמן

**Comment by shantupai** [comment]
איפה אתה?

**Comment by eranws** [comment]
כרגע במייל

איפה אתה

**Comment by shantupai** [comment]
בדיבוץ ופה

**Comment by eranws** [comment]
I think we should focus on the interesting aspects of

### Voice and Text interactions

- Sending text while listening to other rec 🎙️ 🎧
- commenting on a shared recording, public broadcast (e.g. speech of an
expert, politician, ...)

**Comment by shantupai** [comment]
can i send a recording rough here?

**Comment by shantupai** [comment]
[](url)

**Comment by eranws** [comment]
Try drag and drop

**Comment by shantupai** [comment]
"C:\Users\hille\OneDrive\מסמכים\הקלטות קוליות\הקלטה.m4a"

**Comment by shantupai** [comment]
![image](https://user-images.githubusercontent.com/96238593/228925072-4b376dca-cc60-431c-9687-60eb0a6291b0.png)

**Comment by eranws** [comment]
נשמע טוב

**Comment by eranws** [comment]
לתיקיית הקבצים
In the "code" tab

**Comment by shantupai** [comment]
![image](https://user-images.githubusercontent.com/96238593/228925858-4950215f-31f4-4471-b1ac-5d335f27a4b0.png)
