### ISSUE TITLE
תיקונים למאמר שהתפרסם. טעות, שגיאה, מחיקה ותוספת

### ISSUE THREAD

**Issue by eranws** [aansbacher/debate#23]
יש הבדל בין טעות ושגיאה, ארטום לקוריגנדום

Erratum. Notification of an important error made by the journal that affects the publication record or the scientific integrity of the paper, or the reputation of the authors, or of the journal.

Corrigendum. Notification of an important error made by the author(s) that affects the publication record or the scientific integrity of the paper, or the reputation of the authors or the journal. All authors must sign corrigenda submitted for publication. In cases where coauthors disagree, the editors will take advice from independent peer-reviewers and impose the appropriate amendment, noting the dissenting author(s) in the text of the published version.

Retraction. Notification of invalid results. All coauthors must sign a retraction specifying the error and stating briefly how the conclusions are affected, and submit it for publication. In cases where coauthors disagree, the editors will seek advice from independent peer-reviewers and impose the type of amendment that seems most appropriate, noting the dissenting author(s) in the text of the published version.

Addendum. Notification of a peer-reviewed addition of information to a paper, usually in response to readers' request for clarification. Addenda are published only rarely and only when the editors decide that the addendum is crucial to the reader's understanding of a significant part of the published contribution.

**Comment by eranws** [comment]
איזה טירוףףףף אפשר לעשות share
ישר לאישו חדש!!!
ישששש למישו טישו ישששששש למישו טישו
יהש למישהו טישהו
יההש למישההו טישההו
יהוהש למישהוהו טישהוהו
יש

**Comment by shantupai** [comment]
Teruffffff

**Comment by eranws** [comment]
fffffffffffff
fffffffffffff
fffffffffffff
fffffffffffff
fffffffffffff
fffffffffffff
fffffffffffff



--
Eran Weissenstern

**Comment by aansbacher** [comment]
חוץ מהשטויות שבתגובות, אשמח להסבר קצר מה זה Erratum ולמה אנחנו צריכים את זה?
האם זקוקים לאישיו הזה

**Comment by eranws** [comment]
זה מעניין כי יש כאן קטגוריות של ׳טעויות׳ אשר לרוב מבלבלים ביניהן בויכוחים.
1. שגיאה  - אופסי, שגיעת סופרים. לא משנה את המשמעות ודי ברור. המידע שגוי, ארטום=error
2. טעות - התגלה כי החוקר זייף את התוצאות. הטעיה מכוונת. משקרות קופה. המידע מושחת, קוריגנדום=corrupt
