### ISSUE TITLE
ירח חלף

### ISSUE THREAD

**Issue by eranws** [aansbacher/debate#24]
חודש עבר וקשה להבין
מה הצחוק ומה נכון
רמת שיחה או מנת משכל
מה אסול ומה מוטל

ועכשיו ברצינות:
עבר חודש שכולנו יצאנו לחופש חופשי
זמן להתכנס ולשוחח שוב?
לשים את הקלפים על שולחן
ולחלק צ׳יפים וכוסות

**Comment by eranws** [comment]
אוקיי אז למען הסדר הטוב זה אחד של שירים ושטויות
אולי נעשה אחד כזה אחד כזה
צחוק ורצינות
מתובל ותפל
העיקר שייצא

**Comment by aansbacher** [comment]
שאמבלולו

**Comment by eranws** [comment]
Got it, thanks!
--
Eran Weissenstern
