### ISSUE TITLE
משימה: אתר

### ISSUE THREAD

**Issue by eranws** [aansbacher/debate#25]
בעיה:
https://aansbacher.github.io/

מראה הודעת שגיאה:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/770012/236669677-9a94c061-e3f1-4cf4-8a30-192cce6c6311.png">

**Comment by eranws** [comment]
ישנה בעיה
דרושה עזרה
טוב למתחילים
להוסיף משהו
משהו בתיעוד

**Comment by eranws** [comment]
מי שיכול ופנוי אהמ אהמ
<img width="358" alt="image" src="https://user-images.githubusercontent.com/770012/236669910-53d56bba-fed8-4e9e-b5b1-14a17f987ac9.png">
שיעשה לעצמו ASSIGN

**Comment by eranws** [comment]
@aansbacher תעשה תעשה

**Comment by eranws** [comment]
# תלחץ תלחץ
# Settings => Pages
<img width="655" alt="image" src="https://user-images.githubusercontent.com/770012/236673807-911f8812-27b2-4b3d-a37c-d27dc61db989.png">

**Comment by eranws** [comment]
https://aansbacher.github.io/debate

האתר נראה ככה:
<img width="404" alt="image" src="https://github.com/aansbacher/debate/assets/770012/52f98cdc-b33a-40da-9efa-c26e8b57f52f">


@shantupai מה דעתך חתול קסם

יפה ונקי
<img width="1552" alt="image" src="https://github.com/aansbacher/debate/assets/770012/02e4ee8e-7bbb-46a8-8cda-fa8f131c8548">

**Comment by shantupai** [comment]
מעניין פה
