### ISSUE TITLE
תרשים זרימה של הממשק

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#27]
תרשים זרימה של איך הממשק יראה
סיכום של #3 #8 #9 #14

**Comment by aansbacher** [comment]
![תרשים](https://github.com/aansbacher/debate/assets/128156970/f9859c27-13df-41d2-bfcf-5504f50c4868)

**Comment by aansbacher** [comment]
מסך אחד: התחברות
מסך שני+שלישי: בחירת נושא + בעד/נגד
מסך שלישי: בחירת מעורבות בדיבייט.
מסך רביעי: מציאת משתתפים/יריבים
מסך חמישי: הזירה

עצוב - יש בעיה
עיניים - הסתכלו פה
טיל - פתרון שעונה להגדרת הבעיה
לב - חיזוק חיובי, חשמבולו
חיוך - חיזוק חיובי עם תוכן, שכוייעח

**Comment by eranws** [comment]
נראה מ-ע-ו-ו-ל-ה!
אפשר להגדיר את זה עוד אבל מספיק עם כל האישוז... יש כלים יותר טובים.
כל מה שקורה ביניהם זה כבר אפשר לתת למישהו שיעשה את זה בכמה שעות.

@aansbacher אתה יכול להעיף מבט על figma?
אפשר לצייר שם באמת עם כפתורים
figma.com

**Comment by eranws** [comment]
מסתכל בהנאה על התרשים
אכן מרשים איפה זה היה

במבט על אני חושב על
משחקי מחשב כמו פעם
קצת דומה לגאזר

יש לך בכניסה
חיידר ראשון
פקידת קבלה
מי ומה אתה
לוגעי''ן בלעז

חדר שני
חדרי הלבשה שירותים
תחליף בגדים שים כיפה
תלמד את החוקים
ככה מתווכחים
פה אצלנו
בבית הזה

חדר שלישי
מסדרון ארוך
ובו חדרים חדרים חדרים חדרים 
קטנים לאחד על אחד לאימונים
חדרי ישיבות לפלפולים מהנים
וזירות מפוארות לגלדיאטורים
עם חלונות הצצה ומשקפות
וחדרי וי איי פי עם שעון יד 
קיר בעיצוב תלת מימד 
יהלומים מפלסטיק 
ועמייאת עופרת
רדיאטורים

**Comment by eranws** [comment]
קצת מפריע לי התיוג מראש של בעד ונגד
כאילו אני בא להתווכח אבל תוך כדי אני משנה קצת

חשבתי על הממשק שצריך להיות יותר פלואידי כי זה מה שהילדים של היום אוהבים
מזכיר לי פעם תרגיל בפסיכודרמה שהולך כך
- שני הצדדים עומדים בשני הצדדים של החדר ומתווכחים על משהו
- מחליפים דעות דעה דעה תודה רבה מתקרבים מעד אחד
- עוד פעם מה דעתך מה דעתך יופי תתקרבו עוד קצת
- הדימוי של התקרבות כמעט בנאלי כמו פעולה בסניף
- מתישהו אתה חוצה את הגבול לטריטוריה שלו
- עד שבסופו של דבר אתה עומד במקומו
- ואל תדון אדם עד ש אבל גם כש אל
- מה שמך ומי שמך לדיין ותליין
- דעתך דעה והיא לא שלך
- אין מקום ואין טריטוריה
- ואין מפה אז אין גבול
- ואין שלי ואין שלך
- ואין ויכוח או ריב
- ורק שלום ושלווה
- והשקט כן בטח
- בטח בטח
- צנון ורתח
-

**Comment by aansbacher** [comment]
שמע אחי, איזה אתה חריף, ואתה מבין אותי

**Comment by aansbacher** [comment]
מאוד אוהב את הכיוון של ממש להכריח את המתמודדים להציג טענות של הצד השני.

**Comment by aansbacher** [comment]
זו ממש שירה, ערן, אני עף על זה, מה השלב הבא, מה אני צריך לעשות, לכתוב עמוד עמוד מה אני רואה בעיני רוחי?

**Comment by eranws** [comment]
תתאר את מה שאתה רואה
כאילו אתה מספר לחבר שלך על משהו שראית
אתה חייב לראות את זה
זה ממש מגניב
זה מתחיל כזה עם פפם
אורות מציפים את הבמה
ואז מציגים את הנושא
יש ציור של עוגה
מחשיכים את הבמה
 המתמודד הראשון עולה
צלצול פעמון טיימר מתחיל
המתמודד...

**Comment by eranws** [comment]
אם קשה לך לכתוב אז תשורר ואם זה רך מדי אז תשרבב את זה הלאה עד כדי כך

מדברים על השנה שחלפה מאז מקרה התפוח

**Comment by aansbacher** [comment]
אני לוקח את זה לכיוון של עין הנמר (כמו בסטריטבול).
אבל מתלבט אם 'הצגת שחקנים' זה לא יותר מידי...

**Comment by eranws** [comment]
בדיוק ראיתי קטע של גואש בגן הפעמון...
הנה יוצא הסטריטבול, אין יור פייס.
שמת תמונה של זוג מתווכח. מצח-מצח אף-אף
כמעט נשיקה...
למה זה כל כך כיף
ועם זאת כה כואב
קוקו

**Comment by eranws** [comment]
העברתי לדף design.md
