### ISSUE TITLE
הגדרות | חוקים

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#28]
עימות | משתתפים | חוקים | סיבובים | אכיפה | ניקוד

# עימות

דיבייט הוא מפגש *עימות*
בין שני אנשים
אירוע אשר נמשך 10 דקות 
ב-מ-ד-ו-י-ק

הויכוח נעשה בשלושה סיבובים

מפגש בו עמיתים
מוכיחים ומתווכחים
מחליפים דעות
משחיזים רגשות

שני משתתפים
מתחרים ביניהם 
לגבי רעיון כלשהו

חם חריף מעניין
מעציב קשה
בוטה חשוב מעצבן

## משתתפים
- משתתף 2
- צופה 0 או יותר
- שופט 1 או יותר

בכל סיבוב לכל מתמודד יש תור
פעם אחת בה הוא יכול לדבר

## סיבובים
יש שלושה סיבובים:
- 3 דקות
- דקה וחצי
- 30 שניות

---

---
למתמודד המתחרה אין זכות לדבר
אך הוא יכול לבחור האם להגיב
התפרצות כרוכה בקנס כמובן

---

## ניקוד
הניקוד יינתן ע"י הצופים. כל צופה שצפה בסיבוב יוכל לנקד אותו.

### איך נותנים ניקוד?
עבירה נותנת נקודה אדומה
משפט מזכה בנקודה ירוקה
נקודה שחורה משמעותה דין משמעתי, עבירה ברמת הרחקה
נקודה לבנה, כל הכבוד משמעותי

אם מגיעים ל3 מכל סוג נגמר המשחק
ירוק מבטל אדום או שלא
תלוי איפה גדלת

על מה יורד ניקוד (קללות, הסתה, דיבור לא על הנושא.)
על מה עולה ניקוד (טיעונים, נימוס וכבוד, ידע, אסמכתאות)

### ניקוד שלילי
קללות, גידופים, אלימות מילולית,
פנייה, האשמה, השפלה, אישית, הכללה,

### ניקוד חיובי
על משפט?
על היגד?

## אכיפה
שבתור התחלה אפשר לקחת הנחות מקילות בכול התחומים:

שופט אנושי. זה קשה לנתח טקסט ובמיוחד טקסט פוגעני יכול להיות מרומז, או תלוי הקשר.
אפשר לחלק באופן גס לפי תגובה: רעילה, סתומה או מועילה
ניקוד של מינוס שלוש או מספר כלשהו זה כרטיס אדום והפסד, הרחקה לצמיתות.
פלטפורמה של התכתבות. ברור לך שההודעה שלך עוברת איזשהו סינון לפני שהיא מגיעה לצד השני חו״ח, או לציבור קו״ח.
זה די סטנדרטי בפורומים של פעם. יש תפקיד של מנהל תוכן, moderator, צנזור

### שיפוט
אפשרות ראשונה – קהל מצביע בכל סיום סבב
אפשרות שניה - שופט אנושי
אפשרות שלישית - שופט רובוטי
ערבוב שלהם

### שיתוף שיפוט
אפשר שיהיו תפקידים גם לצופים, נגיד משגיח אלימות
וזו גם דרך לצבור ניקוד, אני בתור צופה מקבל נקודות בפלטפורמה ו/או זה נכנס לפרופיל שלי (היה משגיח אלימות בשלושה עימותים וקיבל ציור עובר/לא עובר מהמתמודדים

**Comment by eranws** [comment]
אז זה נושא שחוזר על עצמו שוב ושוב ושוב, ובסוף יש לנו מושג טוב מה הכי בוער:
1. חוקים - מה החוקים. מה אסור ומה מותר. אל תתקרב יותר מדי
2. גבולות גזרה - מה השטח, זירה, ארגז חול. אל תתרחק יותר מדי
3. ניקוד - מקל וגזר, בגבולות המשחק. שחק יפה תקבל פרס, מותר גם להשתולל אבל תקבל מינוס
4. אכיפה - מתי סטופ, זהו נגמר המשחק. עבר הזמן, או כרטיס אדום. אל תתפשט ואל תקלל

**Comment by aansbacher** [comment]
היטבת לבאר

**Comment by eranws** [comment]
אפשר להגיד שזה הכל חוקים
חוקים ותת חוקים
ואיך מפרשים את החוק שזה גם חוק

**Comment by eranws** [comment]
high falutin

נראה טוב ומהודק.
החלק של החוקים והעונשים בעיקר...
מה האינטרס? איפה הפרס? למה לי הסטרס?

 יאללה לדבר עם משקיעים?

**Comment by eranws** [comment]
צריך ואפשר להעביר את מה שכתוב כאן בתיאור לאיזשהו קובץ
@aansbacher משימה בשבילך
תיצור קובץ חדש ותעתיק אליו את התוכן.
- ראה לשונית של `Code`.

חג שמח לקילם 🍰

**Comment by eranws** [comment]
closed with #34

**Comment by eranws** [comment]
עוד בנושא חוקים
https://docs.github.com/en/site-policy/github-terms/github-community-guidelines
