### ISSUE TITLE
Flow לצייר איך האפליקציה תיראה

### ISSUE THREAD

**Issue by aansbacher** [aansbacher/debate#3]
לצייר לי איך האפליקציה תיראה

**Comment by shantupai** [comment]
אולי אתה מקבל התראה: "מישהו חולק על דעתך לגבי רפורמה משפטית, רוצה להתווכח"?

**Comment by eranws** [comment]
מסך 1:

**מישהומשהו86** מזמין אותך לויכוח #3674:
**הנדון:** שוקו בקרטון או בשקית
**מחיר** השתתפות: 100 גולים 
**סכום** הזכייה: 1000 גולות

---

מסך 2:
כיצד תרצה להשתתף:
- בעד קרטון
- בעד שקית
- מאזין
- שופט

---

מסך 3:
[[ דיבייט הויכוח ]]

**Comment by aansbacher** [comment]
![תרשים](https://github.com/aansbacher/debate/assets/128156970/26f2ffeb-8488-40bd-89e5-29becdbab36c)

**Comment by eranws** [comment]
אלף נשיקות
מיליון כוכבים
מיליארד לבבות

**Comment by aansbacher** [comment]
מסך אחד התחברות
מסך שני+שלישי: בחירת נושא + בעד/נגד
מסך שלישי: בחירת מעורבות בדיבייט.
מסך רביעי:מציאת משתתפים/יריבים
מסך חמישי: הזירה

**Comment by eranws** [comment]
עצוב - יש בעיה
עיניים - הסתכלו פה
טיל - פתרון שעונה להגדרת הבעיה
לב - חיזוק חיובי, חשמבולו
חיוך - חיזוק חיובי עם תוכן, שכוייעח

**Comment by eranws** [comment]
@aansbacher אפשר לסגור לענ״ד
נראה שהתרשים הזה משהו טיל לבבות :)
אפשר להמשיך מכאן עם מסמך יותר מפורט של המסכים, או לעבוד עם כלי 
wireframe 

- figma https://www.figma.com/
- canva
