### ISSUE TITLE
לוח השראה | Inspiration

### ISSUE THREAD

**Issue by eranws** [aansbacher/debate#30]
רבנו הצדיק הראה לנו בזמנו דוגמה לממשק דומה
וכל מה שעשינו בחטאינו הרבים זה לנגח אותו
אז מוזמנים לשתף כאן השראות מדברים רלוונטיים
תמונות, צילומי מסך, אפשר גם לינקים תכלס מה שבא לכם
אבל עדיף שיבוא לכם תמונות או צילומי מסך נו כתבתי את זה ראשון

**Comment by eranws** [comment]
## International Karate

## מהלכים מותרים
![image](https://github.com/aansbacher/debate/assets/770012/3886690c-6254-4f5f-b514-6e95342c5732)

## שני מתמודדים, שופטים, קהל - לוח תוצאות!
![image](https://github.com/aansbacher/debate/assets/770012/a032d9ad-ab2d-4e52-9a02-b6131ec75647)

**Comment by eranws** [comment]
עימותים נבחרים ביעדים אקזוטיים
![image](https://github.com/aansbacher/debate/assets/770012/49fa38b8-0211-45cc-9999-e8555b18954d)

![image](https://github.com/aansbacher/debate/assets/770012/8b4ef425-d7ac-4be7-9728-fd2a49f34d1a)

**Comment by aansbacher** [comment]
השאלה אם אנחנו משדרים זירת קרב או לאו דווקא

**Comment by eranws** [comment]
זה מקום לשים פה כל מיני השראות ותמונות מה השאלה

**Comment by aansbacher** [comment]
רות, קיבלתי

**Comment by aansbacher** [comment]
![הורדה (3)](https://github.com/aansbacher/debate/assets/128156970/c48706c5-3c19-4efd-bcdb-4dd209aac8f7)

**Comment by aansbacher** [comment]
![הורדה (2)](https://github.com/aansbacher/debate/assets/128156970/1c7d6893-7f83-4fda-9d4b-c06cefa5940c)
![הורדה (1)](https://github.com/aansbacher/debate/assets/128156970/e29aef7a-7919-421b-b787-dbdeb6a8a77a)

**Comment by aansbacher** [comment]
![הורדה](https://github.com/aansbacher/debate/assets/128156970/c632730b-5ce7-4b67-b9fe-32924ece347f)

**Comment by aansbacher** [comment]
![WhatsApp Image 2023-05-17 at 14 02 44](https://github.com/aansbacher/debate/assets/128156970/61e22fbe-5a4f-4d6f-8108-0d75b3f48aab)

**Comment by aansbacher** [comment]
![WhatsApp Image 2023-05-17 at 14 02 45](https://github.com/aansbacher/debate/assets/128156970/219fc48f-efba-4b95-bff8-cd09ad173ada)

**Comment by aansbacher** [comment]
![WhatsApp Image 2023-05-17 at 14 07 35](https://github.com/aansbacher/debate/assets/128156970/a9512e0a-0e71-4d6d-a11c-3ab2e6b1ebef)

**Comment by aansbacher** [comment]
![WhatsApp Image 2023-05-17 at 14 08 29 (2)](https://github.com/aansbacher/debate/assets/128156970/3ed4176f-1a94-43e0-92da-8c44e356b0ff)

**Comment by shantupai** [comment]
טים בליסטי!
איך מעלים תמונות עוד לא הצלחתי

**Comment by eranws** [comment]
@aansbacher תכול למצוא פה משהו שמכוון לדעתך
https://www.canva.com/templates/?query=chatting-app

<img width="899" alt="image" src="https://github.com/aansbacher/debate/assets/770012/8f9c6899-69fd-481e-9cbd-c186f2a8c4d2">


הסתרתי את התמונות שנמצאות כבר ב#31

**Comment by eranws** [comment]
זוג רב ביניהם. מצח נוגע, אף נוגע - על מה? 
שני אנשים משני צדי המצוק, צועקים אחד על השני עם מגפון. מדוע?
שועלים קטנים מחבלים ומתקוטטים, בלתי, אם נועדו?
תיבה אדומה עם מיקרופון, מולה תיבה כחולה עם מיקרופון, אור ועשן. מתח באוויר?

**Comment by eranws** [comment]
![1](https://github.com/aansbacher/debate/assets/770012/6525c072-5a39-4112-8f53-070041d176a2)

**Comment by eranws** [comment]
![2](https://github.com/aansbacher/debate/assets/770012/3ad8e5e4-dff1-47bd-afab-6c9300656219)
