### ISSUE TITLE
Gameplay | משחקיות

### ISSUE THREAD

**Issue by eranws** [aansbacher/debate#31]
בדיוק כמו שעשית ב#27 לגבי כל האפליקציה. עכשיו יותר מפורט לגבי  **מסך חמישי: הזירה** 
תרשים קצת יותר מפורט של איך זה מתחיל, מסך של חוקים, צלצול פעמון, הגרלה של מי מתחיל...

- אתה יכול להתחיל מגיימפליי רגיל של משחק שאתה מכיר. 
- עכשיו זה החלק המעניין של החוויה, שים לב לפרטים
- כאן זה אמור להראות ייחודי ושונה. בדרך שלך של קילם

תנסה לדמיין את המנגינה של מי רוצה להיות מליונר...
טה, טה טה, טה טה טה, טה טהההההה... סטגדם!

https://en.wikipedia.org/wiki/Gameplay
```
משחקיות היא הדרך הספציפית שבה שחקנים מקיימים אינטראקציה עם משחק, ובמיוחד עם משחקי וידאו. משחקיות היא התבנית המוגדרת באמצעות חוקי המשחק, הקשר בין השחקן למשחק, אתגרים והתגברות עליהם, העלילה והקשר של השחקן אליה. משחקי וידאו נבדלים מרכיבי גרפיקה ושמע. במשחקי קלפים, המונח המקביל הוא משחק
```

**Comment by aansbacher** [comment]
אוקיי, שבוע הבא ביום שני, אשב עמוד עמוד ואנסה לצייר את זה, חלק אני כבר מדמיין

**Comment by eranws** [comment]
נו איך הולייך

**Comment by aansbacher** [comment]
הבנתי חמשלמועחטע

**Comment by aansbacher** [comment]
![WhatsApp Image 2023-05-17 at 14 02 44](https://github.com/aansbacher/debate/assets/128156970/c6588201-39cd-4501-a836-ab54dd354e76)
מסך ראשון (שוב, אני לא מעצב, אבל זה בגדול התוכן של המסך התחברוצ, העיצוב צריך להיות מגניב יותר)
![WhatsApp Image 2023-05-17 at 14 02 45](https://github.com/aansbacher/debate/assets/128156970/6d573705-b911-47af-a3ce-94f4382ae8bb)
כנ"ל לגבי מסך שני - בחירת נושאים


![WhatsApp Image 2023-05-17 at 14 07 35](https://github.com/aansbacher/debate/assets/128156970/c6f7b9b9-68bb-4083-9055-f0758973e7ca)
מסך שלישי בחירת צד? ובחירת מעורבות/השתתפות - צופה/שופט/משתתף

![WhatsApp Image 2023-05-17 at 14 08 29 (1)](https://github.com/aansbacher/debate/assets/128156970/8145afa1-e456-4f8b-97f2-6d139aed0f72)
מסך רביעי - מצאנו לך מת'נגדים

**Comment by aansbacher** [comment]
מסך חמישי - תלוי מאוד האם בשלב הראשון אנחנו הולכים לדיבייט כתיבה או משולב קולי/וידאו.
אני מאוד מעוניין ומקווה למשהו שהוא יותר אינטראקטיבי מאשר רק צ'ט.

בגדול מסך 5 מתחיל בתקנון חוקים.
עם שעון חול (לדוגמה 2 דקות) ובסופו מאשר הקורא/המשתתף את התקנון.
לאחר מכן נכנסים לזירה. פינה ימנית פינה שמאלית
שעון באמצע
דמויות אווטאר של צופים ושופטים למטה.

**Comment by eranws** [comment]
@aansbacher גם אני. צייר לי כבשה
> אני מאוד מעוניין ומקווה למשהו שהוא יותר אינטראקטיבי מאשר רק צ'ט.

א. גם אני. פה המקום לפרט במה זה שונה ממה שקיים היום.

> מסך 5 מתחיל בתקנון חוקים.

ב. נשמע די סטנדרטי. אולי יש פה משהו יוצא דופן (אפשר נגיד לקרוע את הדף של החוקים? ולהיענש אולי... אבל אפשר?)

> יש שעון חול 2 דקות לקרוא ובסוף הזמן מאשר הקורא/המשתתף את התקנון.

ג. מה קורה בסוף? זה חותם על זה ממילא ומכניס אותי בכוח לזירה? זורק אותי לחדר מדרגות? (חוסם לצמיתות?)

> לאחר מכן נכנסים לזירה. פינה ימנית פינה שמאלית
> שעון באמצע
> דמויות אווטאר של צופים ושופטים למטה.

ד. צייר את המסך הזה

**Comment by eranws** [comment]
התמונות ששיתפת פה הן של אפליקציה שלדעתי היא ההפך המדויק והגמור של מה שאתה רוצה.
כפתורים מרובעים בצבעים דהויים של חום, פרנדלי דיבייטר...

אני מדמיין אש פיצוצים
אבל הכל לפי החוקים
נגיד במסך הראשון של האפליקציה - טבלת האלופים. בוא נראה אותך

**Comment by eranws** [comment]
אוקיי בינתיים ראינו שטקסט אסינכרוני במייל עובד מצוין
#36 

> משחקיות היא הדרך הספציפית שבה שחקנים מקיימים אינטראקציה עם משחק, התבנית המוגדרת באמצעות
> - חוקי המשחק
> - הקשר בין השחקן למשחק
> - אתגרים והתגברות עליהם
> - העלילה והקשר של השחקן אליה
