### ISSUE TITLE
מה מטרת החיים 

### ISSUE THREAD

**Issue by shantupai** [aansbacher/debate#32]
האם יש לחיים מטרה? לדעתי זה תלוי בהחלטה סובייקטיבית של האדם.

**Comment by eranws** [comment]
לחיות בשמחה ובהנאה תוך צמצום פגיעה בזולת ושאיפה להיטיב עם כלל האדם והבריאה

**Comment by shantupai** [comment]
מי מגדיר מהי פגיעה ומה נחשב מיטיב

**Comment by eranws** [comment]
אני אתה והוא
אני משתדל לעשות מה שטוב לי
אתה *ו*אני בסביבתנו הקרובה עוזרים זה *ל*זה
הקשר בינינו הוא הגדר ואנו מחליטים כיצד מתחלקים באופן טבעי כמו שמחלקים עוגה
אני מחלק אתה בוחר ככה אף אחד לא יכול להתלונן על החלוקה או הבחירה
השאיפה להיטיב היא הגדר סביב העולם החיצון 
תרומה לאחר שאתה לא ממש מכיר
או זר מוחלט שאתה לא תכיר
אבל הוא פה לידך
ויש לו חיים חלומות ותקוות ואכזבות ומטלות וכביסה וקומפוסט
אז תיטיב גם איתו מ׳כ׳פת׳ך
## `מxכxפתxך | MAXPATXA`

**Comment by eranws** [comment]
מסתומרת מכפתך
׳כפתלי בטח שכפתלי

мазтомерет махпатха?!
махпатха маехпатлый?
барур шехпатлы!

**Comment by eranws** [comment]
# `махпатха? мазтомеретмахпатха?! мазэхпатхамаехпатлый!? баруршехпатлы!`

https://github.com/aansbacher/debate/assets/770012/1b109c41-e30d-41bd-99f6-aa4d131e5ff3

**Comment by eranws** [comment]
לחצתי על הכפתור של [Jump to bottom](https://github.com/aansbacher/debate/issues/32#issue-comment-box)

**Comment by eranws** [comment]
נתראה ונראה עוד ששה שבועות בנושא #42
