### ISSUE TITLE
פיילוט דיבייט: חוקים - בעד או נגד aaaans VS shanti

### ISSUE THREAD

**Issue by shantupai** [aansbacher/debate#36]
- מציע להרים דיבייט ראשון, גרסת ניסוי ראשוני אלפא אלפא, למטרות למידה התנסות וחווי-ה.

- למצוא משתתפים
מועמדות: לפריקון ,בלאו
- להחליט על פורמט; זום/מטהורס/חשבמולו

- לקבוע ביומן
- לקיים מלכות שמים
- להיות סתם

**Comment by eranws** [comment]
אוקיי אז דיבייט
נושא: חוקים - בעד או נגד
משתתף בעד: @aansbacher 
משתתף נגד: @shantupai 
שופט: @eranws 

@aansbacher  אתה מתחיל
כתוב פסקה על חוקים באופן כללי ולמה אתה בעד שיהיה חוקים

יש לכם שלושה ימים להגיב.

ניתן להתייחס לחוקים אלה:
https://aansbacher.github.io/debate/rules

צאו לדרך!

**Comment by aansbacher** [comment]
חוקים זה מסגרת, אם אין חוקים אין דרך לנקד. 
הייתי רוצה שהמשתתף שלא מדבר יושתק בכפייה. והייתי רוצה שמי שמתנהג באלימות יודח מיידית, 

כל שאר הדברים נתונים לפרשנות

**Comment by eranws** [comment]
פתיחה חזקה. שנטיפי תגובתך

**Comment by shantupai** [comment]
מי אמר שצריך לנקד.
כשאתה מנצח בדיבייט זה ברור לכולם.
להגיד מה מותר ומה אסור זה מיותר כי זה לא נכון, הכל אפשר וכל פעולה גורמת לתגובה כלשהי בסבירות כלשהי אז תחליט בעצמך מה נראה לך יקדם את המטרה שלך

**Comment by shantupai** [comment]
להשתיק מישהו זה אלים. אז איך זה יכול לקדם שיח לא אלים.
במקום חוקים אפשר רשימה של פרמטרים שאותם בוחן השופט.
לא צריך חוק שאסור להגיד שטויות לא נכונות, כי מי שיעשה את זה פשוט יצא אהבל

**Comment by eranws** [comment]
אוקיי שנטיפי מינוס אחד על זה שמה שלא היה בסוף דבריך לא שמת נקודה.
ובכלל המשפט האחרון היה מיותר אך נמחל לך, כי התחלת את הסיבוב השני.
@aansbacher 
עכשיו אתה עם שני משפטים

**Comment by eranws** [comment]
@aansbacher אתה מוזמן להגיב ל:
> במקום חוקים אפשר רשימה של פרמטרים שאותם בוחן השופט.
> > חוקים זה מסגרת, אם אין חוקים אין דרך לנקד.

> להשתיק מישהו זה אלים. אז איך זה יכול לקדם שיח לא אלים.
> > הייתי רוצה שהמשתתף שלא מדבר יושתק בכפייה.
> > והייתי רוצה שמי שמתנהג באלימות יודח מיידית,

ובהזדמנות עוד על:
> > כל שאר הדברים נתונים לפרשנות

@shantupai  אולי תפרט עוד על ההיגד הנפלא הזה
> להגיד מה מותר ומה אסור זה מיותר כי זה לא נכון, הכל אפשר וכל פעולה גורמת לתגובה כלשהי בסבירות כלשהי אז תחליט בעצמך מה נראה לך יקדם את המטרה שלך

**Comment by aansbacher** [comment]
לא הבנתי מה צריך לעשות, להגיב

**Comment by shantupai** [comment]
כן תגיב מה לא ראוי בעיניך לתגובה יא קונפורמיסט? 
או שאל תגיב למרות שכבר הגבת
היית מעדיף שיהיה חוק שאומר לך אם להגיב או לא?או להחליט בעצמך? 
למרות שבכל מקרה אתה מחליט בעצמך,חוק או לא חוק.
אתה יודע מה , מה נחשב בעיניך אלימות שבגינה יורדות נקודות?
יום טוב אהויבים

**Comment by aansbacher** [comment]
אפשר לעשות שהשופטים עושים עליך כמו רפורט/דיווח אם אתה מתנהג באלימות, ואם אתה מדווח פעם שנייה אתה מודח.

אני מזכיר שהמטרה היא ללמוד להתווכח נכון, אם אנשים ינצלו את הפלטפורמה להעליב ולבזות אנשים שלא מסכימים איתם, מה עשינו בזה

**Comment by shantupai** [comment]
אני חושב שככל שיש יותר אלמנטים של יחסי כוח כך הלמידה פחות משמעותית ובעלת אפקט עמוק. כמובן שזה לא הגורם היחיד

**Comment by eranws** [comment]
דיון פורה ומעמיק
מאה נקודות לכל אחד
פחות אחד לשנטיפי על האהבל
אבל נדון אותו לכף זכות כי אולי
התכוון לכתוב אהבה.

לדעתי אפשר לחתום את הדיון.
ניתן להמשיך לדון אודות הדיון,
נעשה זאת במה שקרוי בלע''ז
**פי אר** PR

וכעת המתמודדים יקודו קידה וילחצו ידיים
